<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<link rel="shortcut icon" href="imagenes/icono.png">';
echo '<!--Tipografía-->';
echo '<link rel="preconnect" href="https://fonts.googleapis.com">';
echo '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>';
echo '<link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200;400;700&display=swap" rel="stylesheet">';
echo '<!-- Íconos-->';
echo '<script src="https://kit.fontawesome.com/cd41e37ba4.js" crossorigin="anonymous"></script>';
echo '<!--Boootstrap-->';
echo '<link rel="stylesheet" href="css/bootstrap.css">';
echo '<link rel="stylesheet" href="css/style.css">';
echo '';
echo '<title>Inicio | L - Miquelez</title>';
echo '</head>';
echo '<body>';
echo '';
echo '<!--Header-->';
echo '<header id="inicio" class="container-fluid header">';
echo '';
echo '<!--En esta fila va la barra de navegación-->';
echo '<div class="row">';
echo '<div class="col header-nav">';
echo '<nav class="navbar navbar-expand-lg navbar-dark">';
echo '<div class="container-fluid">';
echo '<a class="navbar-brand" href="#"><img  src="imagenes/logo.png" alt="Lisandro Miquelez desarrollo web" width="200px"></a>';
echo '<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">';
echo '<span class="navbar-toggler-icon"></span>';
echo '</button>';
echo '<div class="collapse navbar-collapse botonera" id="navbarText">';
echo '<ul class="navbar-nav me-auto mb-2 mb-lg-0 fs-4">';
echo '';
echo '<li class="nav-item ">';
echo '<a class="nav-link" href="#quienSoy">Quien soy</a>';
echo '</li>';
echo '';
echo '<li class="nav-item ">';
echo '<a class="nav-link" href="#educacion">Educación</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="nav-link " href="#proyectos">Proyectos</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="nav-link" href="#contacto">Contacto</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="nav-link" href="/pages/login.html">Inicio de Sesión</a>';
echo '</li>';
echo '</ul>';
echo '';
echo '</div>';
echo '</div>';
echo '';
echo '</nav>';
echo '</div>';
echo '</div>';
echo '';
echo '<!--En este contenedor va el texto del header-->';
echo '<div class="container-lg contenedor">';
echo '';
echo '<div class="row justify-content-start">';
echo '<div class="col-6">';
echo '<h1 class="display-1">Lisandro Miquelez</h1>';
echo '</div>';
echo '<div class="display-6 icon-lines"><i class="fa-solid fa-feather-pointed"></i></div>';
echo '<div class="row justify-content-start">';
echo '<div class="col-4">';
echo '<h3 class="display-5">Desarrollo Web</h3>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="justify-end-to-center boton">';
echo '<a class="btn btn-lg" href="#contacto">Contacto</a>';
echo '</div>';
echo '';
echo '</div>';
echo '</header>';
echo '';
echo '';
echo '<!--About-->';
echo '<section id="quienSoy" class="container-fluid mt-3">';
echo '<div class="container py-4 contenedor">';
echo '<h2 class="display-6 mb-3 h2-lines">Sobre mí</h2>';
echo '';
echo '<div class="row align-items-center py-3">';
echo '<div class="col-sm-4">';
echo '<img src="imagenes/perfil.jpeg" alt="foto de lisandro miquelez " class="img-fluid">';
echo '</div>';
echo '<div class="col-sm-8 mt-3">';
echo '<p class="fs-4">Mi nombre es Lisandro Miquelez. Además de Desarrollador Web soy Tecnico Electrónico y profesor de música. </p>';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '</section>';
echo '';
echo '';
echo '';
echo '<!--Education-->';
echo '<section id="educacion" class="container-fluid">';
echo '<div class="container py-4 contenedor">';
echo '<h2 class="display-6 mb-3 h2-lines">Educación</h2>';
echo '';
echo '<ul class="row justify-content-center list-unstyled mt-3">';
echo '';
echo '<li class="col-12 card mb-3">';
echo '<div class="row g-0">';
echo '<div class="col-md-4 d-flex align-items-center">';
echo '<div class="edu-img"><img src="imagenes/argProg.png" alt="Norita" class="img-fluid"></div>';
echo '</div>';
echo '';
echo '<div class="col-md-8">';
echo '<div class="card-body">';
echo '<h4 class="card-title display-6 text-center">Argentina Programa</h4>';
echo '<p class="card-text fs-4">Curso de desarrollo web Full Stack.</p>';
echo '<div class="row justify-content-between">';
echo '<div class="col-md"><p class="fs-4"><span class="fw-bolder">Año:</span> 2021-2022 </p></div>';
echo '<div class="col-md text-center"><a href="#" class="btn btn-lg">Más info</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '</li>';
echo '';
echo '<li class="col-12 card mb-3">';
echo '<div class="row g-0">';
echo '<div class="col-md-4 d-flex align-items-center">';
echo '<div class="edu-img"><img src="imagenes/coderhouse.png" alt="Pachorra" class="img-fluid"></div>';
echo '</div>';
echo '';
echo '<div class="col-md-8">';
echo '<div class="card-body">';
echo '<h4 class="card-title display-6 text-center">Desarrollo Web</h4>';
echo '<p class="card-text fs-4">Curso de desarrollo web en donde aprendí sobre el uso de HTML, CSS, SASS, etc. </p>';
echo '<div class="row justify-content-between">';
echo '<div class="col-md"><p class="fs-4"><span class="fw-bolder">Año:</span> 2021 </p></div>';
echo '<div class="col-md text-center"><a href="#" class="btn btn-lg">Más info</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '</li>';
echo '';
echo '<li class="col-12 card mb-3">';
echo '<div class="row g-0">';
echo '<div class="col-md-4 d-flex align-items-center">';
echo '<div class="edu-img"><img src="imagenes/conser.png" alt="Norita" class="img-fluid"></div>';
echo '</div>';
echo '';
echo '<div class="col-md-8">';
echo '<div class="card-body">';
echo '<h4 class="card-title display-6 text-center">Conservatorio de Música - Juan P. Cruz</h4>';
echo '<p class="card-text fs-4">Profesorado de Música, orientación Educación Musical.</p>';
echo '<div class="row justify-content-between">';
echo '<div class="col-md"><p class="fs-4"><span class="fw-bolder">Año:</span> 2013-2020 </p></div>';
echo '<div class="col-md text-center"><a href="#" class="btn btn-lg">Más info</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<li class="col-12 card mb-3">';
echo '<div class="row g-0">';
echo '<div class="col-md-4 d-flex align-items-center">';
echo '<div class="edu-img"><img src="imagenes/escuela.jpeg" alt="Norita" class="img-fluid"></div>';
echo '</div>';
echo '';
echo '<div class="col-md-8">';
echo '<div class="card-body">';
echo '<h4 class="card-title display-6 text-center">E.E.S.T N1</h4>';
echo '<p class="card-text fs-4">Tecnicatura en Electrónica en la escuela industrial de Junín.</p>';
echo '<div class="row justify-content-between">';
echo '<div class="col-md"><p class="fs-4"><span class="fw-bolder">Año:</span> 2008-2011 </p></div>';
echo '<div class="col-md text-center"><a href="#" class="btn btn-lg">Más info</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '</li>';
echo '';
echo '</ul>';
echo '';
echo '</div>';
echo '</section>';
echo '';
echo '<!--Projects-->';
echo '<section id="proyectos" class="container-fluid background-grey">';
echo '<div class="container py-4 contenedor">';
echo '<h2 class="display-6 mb-3 h2-lines">Proyectos</h2>';
echo '<p class="fs-4">Estos son los proyectos realizados:</p>';
echo '';
echo '<div class="row justify-content-center">';
echo '';
echo '<div class="col-lg-6 ">';
echo '<div class="card shadow m-3 card-height1">';
echo '<div>';
echo '<img src="imagenes/portfolio.png" alt="Vuelo a Iruyá" class="img-fluid">';
echo '</div>';
echo '<div class="card-body">';
echo '<h5 class="card-title display-5 text-center">Portfolio</h5>';
echo '<p class="card-text fs-4">Portfolio realizado para el curso Argentina Programa 2da edición </p>';
echo '<div class="row justify-content-between mb-3">';
echo '<div class="col-md"><p class="fs-4"> <span class="fw-bolder">Año:</span> 2022 </p></div><div class="col-md text-center"><a href="https://lmiquelez.github.io/portfolio" class="btn btn-lg">Al sitio</a></div>';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-lg-6 ">';
echo '<div class="card shadow m-3 card-height1">';
echo '<div>';
echo '<img src="imagenes/bordolino.png" alt="Salto Berrondo Oberá" class="img-fluid">';
echo '</div>';
echo '<div class="card-body">';
echo '<h5 class="card-title display-5 text-center">Trovarte</h5>';
echo '<p class="card-text fs-4">Trabajo práctico final para el titulo de desarrollador web entregado por Coder House. </p>';
echo '<div class="row justify-content-between mb-3">';
echo '<div class="col-md"><p class="fs-4"><span class="fw-bolder">Año:</span> 2019 </p></div><div class="col-md text-center"><a href="https://lmiquelez.github.io/" class="btn btn-lg">Al sitio</a></div>';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- <div class="col-lg-6 ">';
echo '<div class="card shadow m-3 card-height1">';
echo '<div>';
echo '<img src="imagenes/barn-swallow.jpg" alt="Nido golondrina" class="img-fluid">';
echo '</div>';
echo '<div class="card-body">';
echo '<h5 class="card-title display-5 text-center">Anidar en Buenos Aires</h5>';
echo '<p class="card-text fs-4">Ciudad de Buenos Aires o Ciudad Autónoma de Buenos Aires (CABA) también llamada Capital Federal, por ser la sede del gobierno nacional, es la capital y ciudad más poblada de la República Argentina. Tiene sus propios poderes ejecutivo, legislativo y judicial.  </p>';
echo '<div class="row justify-content-between mb-3">';
echo '<div class="col-md"><p class="fs-4"><span class="fw-bolder">Año:</span> 2021 </p></div><div class="col-md text-center"><a href="https://es.wikipedia.org/wiki/Buenos_Aires" class="btn btn-lg">Al sitio</a></div>';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '</div> -->';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '</section>';
echo '';
echo '<!--Contact-->';
echo '<section id="contacto" class="container-fluid">';
echo '<div class="container py-4 contenedor">';
echo '<h2 class="display-6 mb-3 h2-lines">Contacto</h2>';
echo '';
echo '<div class="row">';
echo '<div class="col-lg-4">';
echo '<div class="card shadow card-height mb-3">';
echo '<div class="contact-img fs-3">';
echo '<i class="fa-solid fa-house"></i>';
echo '</div>';
echo '<div class="card-body mb-3">';
echo '<h5 class="card-title text-center fs-3">UBICACIÓN</h5>';
echo '<p class="card-text text-center fs-5">Junín, Buenos Aires, Argentina</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-lg-4">';
echo '<div class="card shadow card-height mb-3">';
echo '<div class="contact-img fs-3">';
echo '<i class="fa-solid fa-envelope"></i>';
echo '</div>';
echo '<div class="card-body mb-3">';
echo '<h5 class="card-title text-center fs-3">EMAIL</h5>';
echo '<p class="card-text text-center fs-5">lmiquelez@hotmail.com</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-lg-4">';
echo '<div class="card shadow card-height mb-3">';
echo '<div class="contact-img fs-3">';
echo '<i class="fa-solid fa-hashtag"></i>';
echo '</div>';
echo '<div class="card-body mb-3">';
echo '<h5 class="card-title text-center fs-3">SOCIAL MEDIA</h5>';
echo '<p class="card-text text-center fs-4">';
echo '<a href="https://github.com/lmiquelez"><i class="fa-brands fa-github"></i></a>';
echo '<a href="https://www.linkedin.com/in/lisandro-miquelez-014347227/"><i class="fa-brands fa-linkedin"></i></a>';
echo '<a href="https://www.instagram.com/lichi_miquelez/?hl=es"><i class="fa-brands fa-instagram"></i></a>';
echo '<a href="https://www.facebook.com/lmiquelez/"><i class="fa-brands fa-facebook"></i></a>';
echo '</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="row">';
echo '<div class="col p-3 shadow mt-3">';
echo '<form name="formulario" action="#" method="post">';
echo '<div class="row g-3 py-3">';
echo '<div class="col-md-6">';
echo '<input type="text" class="form-control fs-5" placeholder="Ingresá tu nombre" aria-label="Ingresa tu nombre" required name="nombre">';
echo '</div>';
echo '<div class="col-md-6">';
echo '<input type="email" class="form-control fs-5" placeholder="Ingresá tu correo" aria-label="Ingresa tu correo" id="inputEmail" required name="email">';
echo '</div>';
echo '<div class="col">';
echo '<textarea class="form-control fs-5" placeholder="Dejame tus comentarios" style="height: 100px" required name="mensaje"></textarea>';
echo '</div>';
echo '</div>';
echo '<button type="submit" name="submit" class="btn btn-lg">Enviar mensaje</button>';
echo '</form>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '</section>';
echo '';
echo '<!--Footer-->';
echo '<footer>';
echo '<div class="row">';
echo '<div class="col gy-3 footer text-dark">';
echo '<p class="text-center mt-3">Proyecto de portfolio  en el marco de la capacitación Argentina Programa - 2022</p>';
echo '</div>';
echo '</div>';
echo '</footer>';
echo '<!--Bootstrap-->';
echo '<script src="js/bootstrap.min.js"></script>';
echo '</body>';
echo '</html>';
?>